### ISSUE TITLE
TFS Gated Check-in run eslint

### ISSUE THREAD

**Issue by DoctaWorm** [madskristensen/WebAnalyzer#12]
I guess this isn't so much a Web Analyzer issue as it is TFS issue, is there away to either use Web Analyzer with TFS for gated check-ins or anyway to get eslint to run when trying to check in and prevent any check in that fails the eslinting process? 

Ideas? Right now I can only think of making a C# unit test that runs command lines and grabs the output of why it failed.

**Comment by madskristensen** [comment]
You can run ESLint on the command line by using node.js. If a .eslintrc file exist in your project then it will be used by both node.js and this extension.

This extension only works in VS.

**Comment by DoctaWorm** [comment]
We got a Unit Test that fires off for gated check-ins that solved our issue, and enforcing our javascript standards.
