### ISSUE TITLE
Error output improvements

### ISSUE THREAD

**Issue by SteveALee** [madskristensen/WebAnalyzer#15]
* The error output windows is not automatically displayed if there are errors. Thus no idea if are any.
* there is no indication of where the errors are coming from (see [image](https://cloud.githubusercontent.com/assets/618922/11823145/567a7e02-a36a-11e5-92dc-a90a794940cb.png) - the errors should indicate they come from ESLint

**Comment by madskristensen** [comment]
None of the errors from the image are coming from Web Analyzer

**Comment by madskristensen** [comment]
This extension will activate the error list when errors occur. The errors you show in the image are not coming from this extension but for the Node.js language service

**Comment by SteveALee** [comment]
OK, any idea how I determine where they are coming from?

**Comment by madskristensen** [comment]
It's up to the language service implementer to specify the Tools and Code column in the error list. Web Analyzer sets both like this:

![screenshot_1](https://cloud.githubusercontent.com/assets/1258877/11823709/68502766-a32a-11e5-835a-10b585063b76.png)

**Comment by SteveALee** [comment]
Ah, we crossed message - thanks. I'll pass on to NTVS for now.
