### ISSUE TITLE
The extension fails silently if node.exe is not found in any of the PATH directories

### ISSUE THREAD

**Issue by dee-see** [madskristensen/WebAnalyzer#16]
Nothing much to add to the title. 

If it's a hard requirement, an error message would be nice. Perhaps an option in the settings to give a specific path for node.exe would be nice as well.

**Comment by madskristensen** [comment]
Does it fix it if you delete `%localappdata%\temp\WebAnalyzer1.xx`?

**Comment by dee-see** [comment]
I closed VS, deleted `%localappdata%\temp\WebAnalyzer1.xx` and then reopened VS and I still have the issue.

I'm tracing with [procmon](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) and I can see devenv.exe is still scanning my path to find node.exe.

**Comment by madskristensen** [comment]
Fixed it version 1.7
