### ISSUE TITLE
Is there a way to ignore files or folders?

### ISSUE THREAD

**Issue by josemarcenaro** [madskristensen/WebAnalyzer#17]
Using Web Analyzer v 1.5.62

I tried creating a .eslintignore file in the project root, and even on the user profile folder, but it does not seem to work.

Is there a way to exclude a folder (i.e. /js/vendor ) from the analysis?

Thanks in advance,
Jose

**Comment by madskristensen** [comment]
I've just added `\vendor\` to the default ignore list. You can ignore files and folders in _Tools -> Options -> Web -> Analyzer_.

**Comment by josemarcenaro** [comment]
Oops - I didn't notice the Options setting for ignoring files and folders. I deserve a RTFM !
Thank you very much.  Jose

**Comment by isc30** [comment]
Hi, is there any way to have this ignore list in a file? that would be really nice as it can be shared between team members on the repo
