### ISSUE TITLE
"The parameter is incorrect" exception in VS 2015

### ISSUE THREAD

**Issue by artin-phares** [madskristensen/WebAnalyzer#18]
VS 2015 > Tools > Web Analyzer > Edit ESLint settings > ...

![9a2297e126b44d5d6b3780bae957b149](https://cloud.githubusercontent.com/assets/671082/12035813/2859e016-ae51-11e5-98f3-9cf76412bf6a.png)

+ no context menu "Run Web Analyzer" option for .js files
+ no errors/warnings in Error List

.eslintrc is in project root
details on installed extensions and versions are here: [versions.txt](https://github.com/madskristensen/WebAnalyzer/files/74000/versions.txt)

**Comment by madskristensen** [comment]
What project type is open? ASP.NET WebForms, Node.js, C# Console project, or...?

**Comment by artin-phares** [comment]
@madskristensen, it was asp.net web project.

I confirm I do not see this issue in v1.6
No 'parameter is incorrect' error anymore, context menu option is in place... but still I do not see any errors/warnings after analyzing in Error List... though this may be another issue.
