### ISSUE TITLE
Configure Linter to look at Solution/Project Directory for .eslintrc

### ISSUE THREAD

**Issue by DoctaWorm** [madskristensen/WebAnalyzer#2]
Is there a way like how Web Essentials 2013 could add the linting file to solution rather than having to have multiple different .eslintrc per machine that may have different configurations across a team?

I wasn't able to find any instructions on how to go about doing this for this tool.

**Comment by madskristensen** [comment]
Yes, it will find the first .eslintrc file it finds up the folder hierarchy and if it can't find one, it will use the one in your user profile

**Comment by DoctaWorm** [comment]
Thanks! That works! 

Also could you add support for eslint-config-airbnb to be included in the WebLinter1.0.31\node_modules

**Comment by madskristensen** [comment]
Great idea. I'll add the most common configs including airbnb

**Comment by madskristensen** [comment]
You now have all the default configs, including airbnb, in the latest CI build. Get it here http://vsixgallery.com/extension/36bf2130-106e-40f2-89ff-a2bdac6be879/

There's a lot of awesomeness in the new build including significant performance improvements

**Comment by DoctaWorm** [comment]
Awesome! Thanks a lot!
