### ISSUE TITLE
No output in error pane

### ISSUE THREAD

**Issue by michaelw85** [madskristensen/WebAnalyzer#20]
I'm running ESLint using grunt which shows some errors for a specific file. When i open up that same file in VS there are no errors visible in the error pane. The .eslintrc file is in the project root but to make sure WebAnalyzer is using the same config i copy pasted the config into the config inside my user dir.
If I right click in the solution explorer on this file the option to "clear errors" is visible so I'm assuming it actually did find something. 

To exclude any issues with my settings I also created an empty solution, added a js file with errors and reset the WebAnalyzer settings. Same issue.

Any idea's how to debug this issue? I would really like to use this plugin.

Kind Regards,
Michael

**Comment by madskristensen** [comment]
Should be fixed in version 1.7
