### ISSUE TITLE
TSLint not working

### ISSUE THREAD

**Issue by craigbroadman** [madskristensen/WebAnalyzer#22]
I have created a brand new solution with a typescript file "test.ts" (as below) but I am not getting any TSLint errors (no semi colon, max line length, type def etc).

test.ts:

module test {
    export class MyTest {
        public doIt = (param) => {
            if (param) {
                console.log("RAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAHRAH");
            }
        }
    }
}

Screen shot:
![image](https://cloud.githubusercontent.com/assets/5638263/12715701/a6343260-c8d3-11e5-8a33-bdf4407a1842.png)

**Comment by madskristensen** [comment]
What type of project is it? MVC, Cordova, Universal Window App, or...?

**Comment by craigbroadman** [comment]
It is just a brand new, empty Web application...

**Comment by craigbroadman** [comment]
[WebApplication1.zip](https://github.com/madskristensen/WebAnalyzer/files/121346/WebApplication1.zip)

See test.ts

**Comment by madskristensen** [comment]
Thanks for the repro project. However, I can see the errors just fine:

![screenshot_1](https://cloud.githubusercontent.com/assets/1258877/12890966/ba199c18-ce3a-11e5-9360-47084a8b4b92.png)

Did you modify any of the TSLint settings? You may have to reset the settings from **Tools -> Web Analyzer -> Reset All Settings...**

**Comment by craigbroadman** [comment]
I have uninstalled and reinstalled the extensions and this seems to be working now...
