### ISSUE TITLE
Uninstall not cleaning up

### ISSUE THREAD

**Issue by marknadig** [madskristensen/WebAnalyzer#32]
I uninstalled the plugin, but I'm still seeing Tools: Web Code Analysis in the menu and context menu from Solution Explorer. Seems it's still "in there". Any suggestions on how to remove all the bits?
Thank you.

**Comment by SeanSobey** [comment]
Any chance you have [ASP.Net tools](https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935?SRC=VSIDE) installed? It contains this extension. If not maybe try clear MEF cache (**%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache**).

**Comment by madskristensen** [comment]
This is because you've installed the ASP.NET Core RC2 Preview tools. It contains linting support modelled after this extension, so it may appear as if this extension is still installed but it's not :)

**Comment by marknadig** [comment]
+1 sorry for the trouble, thanks for your good work on this plugin
