### ISSUE TITLE
Visual Studio 2015 freezes

### ISSUE THREAD

**Issue by subramn** [madskristensen/WebAnalyzer#33]
when any javascript file is  opened suddenly freezes after disabling webanalyzer it works fine

**Comment by SeanSobey** [comment]
Looks like web analyzer has now been included in [ASP.Net tools](https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935?SRC=VSIDE). Uninstalling this extension and installing the ASP.Net tools got it working fine for me.

**Comment by madskristensen** [comment]
Yes, uninstall like @R2dical mentioned fixes it
