### ISSUE TITLE
JSX infers displayName automatically

### ISSUE THREAD

**Issue by beruic** [madskristensen/WebAnalyzer#37]
I'm getting errors that my components are missing a display name.
Following https://facebook.github.io/react/docs/jsx-in-depth.html#the-transform, the `displayName` is infered automatically from variable asignment, which I use.

**Comment by madskristensen** [comment]
That's a rule of ESLint. You can disable that rule by going to Tools -> Web Code Analysis -> Edit ESLint settings

**Comment by beruic** [comment]
Well... I guess you mean [Tools > Web Analyser > Edit ESLint settings (.eslintrc)]. I have several of those:
![screenshot](https://cloud.githubusercontent.com/assets/724716/16124198/427f3e50-33ee-11e6-9324-cbb7788e3b14.png)

**Comment by madskristensen** [comment]
You have several of those because when you install the ASP.NET RC2 Preview 1 tooling, then you should uninstall the Web Analyzer extension. The features are now built in.
