### ISSUE TITLE
Add multilples entries to Tools Menu

### ISSUE THREAD

**Issue by Avaruz** [madskristensen/WebAnalyzer#38]
I uninstall again for the same thing at the moment I had 4 entries with **Web Code Analisis** submenus.
![image](https://cloud.githubusercontent.com/assets/690375/16152340/6c01c3fc-346f-11e6-8951-2903d152ef0d.png)
![image](https://cloud.githubusercontent.com/assets/690375/16152370/988a33c8-346f-11e6-8121-7672104e3a6d.png)

**Comment by madskristensen** [comment]
It looks like the extension didn't get properly uninstalled. Make sure the extension is completely gone from **Extensions and Updates...** dialog. If that doesn't help, try [clearing the MEF cache](https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd)?
