### ISSUE TITLE
Context menu duplicates

### ISSUE THREAD

**Issue by sergey-chanaev** [madskristensen/WebAnalyzer#39]
Since a while I've got duplicates in context menu. I do have VS 2015 Update 2. Have a look onto attached screenshot.

![untitled](https://cloud.githubusercontent.com/assets/13337789/16177050/3b150218-3622-11e6-884e-01e7aaa24582.png)

**Comment by madskristensen** [comment]
Uninstall Web Analyzer. It's built in to the latest ASP.NET Web Tooling and that causes the duplication
