### ISSUE TITLE
Duplicate menus

### ISSUE THREAD

**Issue by vbjay** [madskristensen/WebAnalyzer#40]
![image](https://cloud.githubusercontent.com/assets/3629489/16641936/99392018-43d3-11e6-9c42-45083cc8b95a.png)

**Comment by vbjay** [comment]
Disabling extension removes all but one menu.  Reenabling makes it go back to 4.

**Comment by madskristensen** [comment]
That one menu comes from the ASP.NET Core Preview tooling.

**Comment by ghost** [comment]
So is there a fix for this because I've been getting the 4 menus also. I even uninstalled it today and reinstalled it, but it still shows the same thing as in the screen shot above.

**Comment by madskristensen** [comment]
Dont reinstall it. Leave it uninstalled
