### ISSUE TITLE
Extension Disabled

### ISSUE THREAD

**Issue by Andy65** [madskristensen/WebAnalyzer#42]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.7.77
### Description

I keep enabling this extension and it keeps getting disabled by something else and I have no idea what or why.
### Steps to recreate

No specific steps - this presumably is a problem for you or it is not.
### Current behavior

The extension keeps getting disabled.
### Expected behavior

When enabled the extension should stay enabled until I manually disable it.

**Comment by madskristensen** [comment]
This should fix it https://github.com/remcoros/DuplicateExtensionFinder
