### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by dontera** [madskristensen/WebAnalyzer#5]
I am attempting to install this in VS 2013, but the installer claims that is not a supported version. Can you tell us what versions are supported by this extension, and whether 2013 will be supported?

**Comment by madskristensen** [comment]
This is for VS2015 only. Other extensions such as Web Essentials provides similar functionality for VS2013, so this extension will not be ported to VS2013. This is largely due to the use of APIs that are only available in VS2015
