### ISSUE TITLE
Automatic updates break the extension

### ISSUE THREAD

**Issue by Blackbaud-BrianCrawford** [madskristensen/WebAnalyzer#7]
Each time this extension is updated the new %temp%\WebAnalyzer{version} folder doesn't contain the prepare.cmd and server.js files.  The folder for the previous version is still there in %temp% with those files.  This breaks the extension such that linting doesn't occur at all when opening or saving a file.  With previous updates I had to uninstall, re-start VS, delete the temp folders, re-install, re-start VS and it would work.  With the recent 1.4.48 update, none of this works.

**Comment by madskristensen** [comment]
Fixed
