### ISSUE TITLE
Add an option to make tslint results count as error

### ISSUE THREAD

**Issue by pgatilov** [madskristensen/WebAnalyzer#8]
Perhaps this should be fixed by the tslint team (they even have https://github.com/palantir/tslint/issues/345). However, at this point tslint does not distinguish error severity.

I would like Web Analyzer to count any output of tslint as an error. We are starting a new project and this option could enforce discipline. Since not everyone might be this lucky to have no errors, this clearly should be an opt-in.

**Comment by richardversluis** [comment]
I would like this too. Reading the intro of this repository it looks like it is supported:

> The individual rules for each linter can be configured to be either an error or a warning.

But I haven't figured out how.

**Comment by pgatilov** [comment]
@richardversluis I believe that sentence refers to configuration files of corresponding linters. At least ES and CSS linters allow assigning warning/error level to each rule. Don't know about CoffeeScript. So the problem is that TSLint does not have that feature yet.

**Comment by richardversluis** [comment]
:+1:
